# Setup

In [0]:
!pip install --upgrade scikit-image

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


# Template Matching

In [0]:
import numpy as np
from skimage import feature, io, color, transform
import numpy.linalg as npla
import os
from tqdm import tqdm 
from copy import copy

def template_match(im, data_folder, samples=20):

    im = color.rgb2gray(im)

    types = ['bishop', 'king', 'knight', 'pawn', 'queen', 'rook']
    
    errors = np.zeros(len(types))

    for idx, piece in enumerate(types):    
        err = []
        neighbor_list = os.listdir(data_folder + piece)

        for idx2, ngbr_name in tqdm(enumerate(neighbor_list), total=samples, desc=piece):
        # for idx2, ngbr_name in enumerate(neighbor_list):
            
            name = data_folder + piece + '/' + ngbr_name 

            if name[-3:] == 'npy':
                hog_name = name
                jpg_name = copy(name[:-8]) + '.jpg'
            else:
                jpg_name = name
                hog_name = copy(name[:-4]) + '.hog.npy'
            
            if not os.path.exists(hog_name):
                break

            f_ngbr = np.load(hog_name)

            ngbr = color.rgb2gray(io.imread(jpg_name))
            
            im = transform.resize(im, (ngbr.shape), anti_aliasing=True)
        
            f_im = feature.hog(im)
            
            err.append(npla.norm(f_im - f_ngbr))

            if idx2 > samples-1:
                break
                
        errors[idx] = np.mean(np.asarray(err))
    
    sel_piece = types[np.argmin(errors)]

    return sel_piece, errors

In [0]:
data_folder = '/content/gdrive/My Drive/Visual Chess Recognition/training_images/'

recog = []
names = []
errors = []

check_folder = '/content/gdrive/My Drive/Visual Chess Recognition/Test/Pieces/White/'

for i, im_name in enumerate(os.listdir(check_folder)):
    print('i: ' + str(i))
    im = io.imread(check_folder + im_name)
    piece, errs = template_match(im, data_folder, samples=100)
    recog.append(piece)
    errors.append(errs)
    names.append(im_name)
    print()
    print(piece)
    print(errs)
    print(im_name)
    print()

bishop:   2%|▏         | 2/100 [00:00<00:05, 17.29it/s]

i: 0


bishop:   2%|▏         | 2/100 [00:00<00:05, 18.65it/s]


pawn
[27.90279468 28.3553266  27.85994151 27.44551085 27.7522318  28.10563846]
46.jpg

i: 1


rook: 100%|██████████| 100/100 [00:05<00:00, 18.63it/s]



pawn
[28.28301434 28.97578895 28.35529414 27.83736576 28.36228319 28.45653415]
47.jpg

i: 2


rook: 100%|██████████| 100/100 [00:05<00:00, 18.48it/s]



pawn
[27.70144088 28.28850419 27.75532075 27.2042262  27.75149668 27.8938775 ]
22.jpg

i: 3


rook:  99%|█████████▉| 99/100 [00:05<00:00, 19.55it/s]



pawn
[27.29489265 28.18517286 27.55210839 26.67697405 27.57688252 27.64909951]
62.jpg

i: 4


rook: 100%|██████████| 100/100 [00:05<00:00, 19.38it/s]



pawn
[27.17486887 27.74245974 27.22311043 26.46911405 27.31482879 27.2255237 ]
38.jpg

i: 5


rook:  99%|█████████▉| 99/100 [00:05<00:00, 18.90it/s]



pawn
[27.93550697 28.75730712 27.99697021 27.47524149 28.05864151 28.13276242]
55.jpg

i: 6


rook: 100%|██████████| 100/100 [00:05<00:00, 18.48it/s]



pawn
[28.28658656 28.79275627 28.3559803  27.91606001 28.3422832  28.63935782]
23.jpg

i: 7


rook: 100%|██████████| 100/100 [00:05<00:00, 19.35it/s]



pawn
[27.97991766 28.42974759 28.05479263 27.36411757 27.94819783 28.24524364]
15.jpg

i: 8


rook: 100%|██████████| 100/100 [00:05<00:00, 19.19it/s]



pawn
[28.01667528 28.92935137 28.22320061 27.67859391 28.30062798 28.25937209]
63.jpg

i: 9


rook: 100%|██████████| 100/100 [00:05<00:00, 19.40it/s]



pawn
[27.73329164 28.23426667 27.85808975 27.10560835 27.7170746  28.0199448 ]
14.jpg

i: 10


rook: 100%|██████████| 100/100 [00:05<00:00, 17.86it/s]



pawn
[27.96002948 28.76488361 28.11637058 27.2646855  28.05665443 28.09382684]
39.jpg

i: 11


rook: 100%|██████████| 100/100 [00:05<00:00, 18.94it/s]



pawn
[28.38329923 28.79725061 28.46208874 27.7624495  28.37900743 28.58185738]
7.jpg

i: 12


rook: 100%|██████████| 100/100 [00:05<00:00, 18.44it/s]



pawn
[27.44011397 27.92004316 27.56582459 26.70654861 27.39664811 27.63465765]
6.jpg

i: 13


rook: 100%|██████████| 100/100 [00:05<00:00, 18.41it/s]



pawn
[27.18888207 27.86842686 27.29015305 26.70868054 27.18555641 27.44417089]
54.jpg

i: 14


rook: 100%|██████████| 100/100 [00:05<00:00, 17.96it/s]


pawn
[27.32378198 28.03247317 27.32171169 26.77156642 27.38502782 27.2563375 ]
30.jpg



In [0]:
np.save('recog', recog)
np.save('errors', errors)
np.save('names', names)

In [0]:
for i in range(len(errors)):
    print(names[i])
    print(np.argsort(errors[i]))

46.jpg
[3 4 2 0 5 1]
47.jpg
[3 0 2 4 5 1]
22.jpg
[3 0 4 2 5 1]
62.jpg
[3 0 2 4 5 1]
38.jpg
[3 0 2 5 4 1]
55.jpg
[3 0 2 4 5 1]
23.jpg
[3 0 4 2 5 1]
15.jpg
[3 4 0 2 5 1]
63.jpg
[3 0 2 5 4 1]
14.jpg
[3 4 0 2 5 1]
39.jpg
[3 0 4 5 2 1]
7.jpg
[3 4 0 2 5 1]
6.jpg
[3 4 0 2 5 1]
54.jpg
[3 4 0 2 5 1]
30.jpg
[3 5 2 0 4 1]
